-- MySQL Script generated by MySQL Workbench
-- Thu Jul  5 23:38:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `gender` VARCHAR(45) NULL,
  `imagePath` VARCHAR(45) NULL,
  `videoPath` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieGender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieGender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieGender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieGender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Movie` (
  `User_id` INT NOT NULL,
  `Movie_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Movie_id`),
  INDEX `fk_User_has_Movie_Movie1_idx` (`Movie_id` ASC),
  INDEX `fk_User_has_Movie_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_Movie_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Movie_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_MovieGender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_MovieGender` (
  `Movie_id` INT NOT NULL,
  `MovieGender_id` INT NOT NULL,
  PRIMARY KEY (`Movie_id`, `MovieGender_id`),
  INDEX `fk_Movie_has_MovieGender_MovieGender1_idx` (`MovieGender_id` ASC),
  INDEX `fk_Movie_has_MovieGender_Movie1_idx` (`Movie_id` ASC),
  CONSTRAINT `fk_Movie_has_MovieGender_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_MovieGender_MovieGender1`
    FOREIGN KEY (`MovieGender_id`)
    REFERENCES `mydb`.`MovieGender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_MovieGender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_MovieGender` (
  `User_id` INT NOT NULL,
  `MovieGender_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `MovieGender_id`),
  INDEX `fk_User_has_MovieGender_MovieGender1_idx` (`MovieGender_id` ASC),
  INDEX `fk_User_has_MovieGender_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_MovieGender_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_MovieGender_MovieGender1`
    FOREIGN KEY (`MovieGender_id`)
    REFERENCES `mydb`.`MovieGender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
